name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Quan trọng: Để GitHub lấy được thư mục theme
          fetch-depth: 0         # Lấy toàn bộ lịch sử để Hugo có thể tính toán ngày cập nhật

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3 # Cập nhật lên v3 để ổn định hơn
        with:
          hugo-version: "0.134.3"
          extended: true

      - name: Build website
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true